---
- name: Install Nagios (Ubuntu)
  apt:
    name: nagios3-core
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: start nagios (Ubuntu)
  service:
    name: nagios3
    state: restarted
    enabled: true
  when: ansible_distribution == "Ubuntu"

- name: install nagios reqs (Ubuntu)
  apt:
   name:
    - libpng-dev
    - libfreetype6-dev
    - gcc
    - libc6-dev
    - apache2
    - php
    - libgd-dev
   state: latest
  when: ansible_distribution == "Ubuntu"
